'use client'
import { useState, type ReactNode } from 'react'
import Link from 'next/link'
import { AppShell } from '@/components/layout/AppShell'
import { cn } from '@/lib/utils'
import { ChevronDown, ChevronUp, AlertCircle, CheckCircle, ExternalLink } from 'lucide-react'

// ── Types ─────────────────────────────────────────────────────────────────────

interface FAQ {
  q: string
  a: string | ReactNode
  category: string
  flag?: 'caution' | 'strength' | 'technical'
}

// ── FAQ data ──────────────────────────────────────────────────────────────────

const FAQS: FAQ[] = [
  // ── Model validity ────────────────────────────────────────────────────────
  {
    category: 'Model Validity',
    flag: 'technical',
    q: 'How was the DeBERTa model trained? Can you reproduce the results?',
    a: `The model is microsoft/deberta-v3-base with LoRA adapters (r=16, α=32, target modules: query_proj, value_proj). It was fine-tuned on a 74,288-sample behavioral text dataset using the PEFT library. Training ran for approximately 18,000 steps with AdamW (lr=2e-4, warmup=500 steps, cosine decay). The best checkpoint was selected on macro-F1 on a held-out validation set. Reproducing results requires the checkpoint file, the LoRA adapter config, and the same tokenizer (deberta-v3-base). The training script is in ml/nlp/trainer.py.`,
  },
  {
    category: 'Model Validity',
    flag: 'caution',
    q: 'The training dataset of 74,288 samples — where does it come from? Is it labeled by humans?',
    a: `The dataset was assembled from three sources: publicly available behavioral interview transcripts with researcher annotations, structured coaching session logs with outcome labels, and augmented data generated by paraphrasing high-confidence samples. All samples were reviewed at the programmatic validation stage (L1 confidence weight 0.20). Higher-confidence samples passed recruiter annotation review (L3 weight 0.70). The dataset is not a purely human-labeled gold standard — this is acknowledged in the Known Limitations document. The macro-F1 of 82.4% was computed on a held-out test split drawn from the same distribution as training, which limits claims about out-of-distribution generalization.`,
  },
  {
    category: 'Model Validity',
    flag: 'strength',
    q: 'What does macro-F1 82.4% actually mean in practice? Is that good?',
    a: `Macro-F1 averages F1 across all classes equally, regardless of class frequency. 82.4% across four dimensions (confidence, stress, hesitation, communication structure) means the model is substantially better than chance on all classes, including minority ones. For comparison, a majority-class baseline on behavioral text classification typically achieves 40–55% macro-F1 depending on class balance. 82.4% is competitive with published results on similar behavioral NLP tasks. However, real-world performance depends on input quality: poor microphone, heavy accent, or very short sessions will degrade accuracy below the benchmark figure. The calibration system acknowledges this by assigning reliability tiers and flagging insufficient-data sessions.`,
  },
  {
    category: 'Model Validity',
    flag: 'caution',
    q: 'Are you making any predictive claims about job performance?',
    a: `No. NeuroSync does not predict job performance, hiring success, or any future outcome. The system measures behavioral signals during a session — confidence, stress, communication quality, engagement — and presents evidence to a human decision-maker. The platform is explicitly designed to support recruiter judgment, not replace it. Every report includes a disclosure: NeuroSync provides structured evidence. All decisions remain with the recruiter. Behavioral forecasts (via CBIP) predict behavioral growth trajectories only — never hiring outcomes.`,
  },

  // ── System design ─────────────────────────────────────────────────────────
  {
    category: 'System Design',
    flag: 'technical',
    q: 'Why SQLite instead of PostgreSQL? Can this scale?',
    a: `SQLite with WAL mode handles concurrent reads efficiently for single-node deployments. For a tool used within a single organization — a recruiting team, a coaching program, an enterprise HR platform — SQLite is appropriate and avoids operational overhead. The query patterns are predominantly reads (session retrieval, narrative generation), with writes only during live sessions. PostgreSQL becomes necessary at horizontal scale (multiple application servers) or at very high concurrent session counts (100+ simultaneous). A migration path is modelled: the application uses an internal DB abstraction, and the DATABASE_URL config field is documented. The honest answer is: SQLite is the right choice for the demo and early deployment phase; PostgreSQL is the right choice at scale, and we have not built that migration yet.`,
  },
  {
    category: 'System Design',
    flag: 'technical',
    q: 'Why WebSocket instead of HTTP polling for real-time analytics?',
    a: `Polling at 500ms would produce 120 HTTP requests per minute per session. At any meaningful scale (10 concurrent sessions = 1,200 requests/minute from streaming alone), this saturates the server with overhead traffic. WebSocket maintains a single persistent connection per session, pushes only when new analytics are available, and eliminates redundant round-trips. The tradeoff is connection state management (reconnection logic, ping/keepalive) — but this is well-handled by the useWebSocket hook with exponential backoff reconnection.`,
  },
  {
    category: 'System Design',
    flag: 'caution',
    q: 'ScriptProcessor is deprecated in the Web Audio API. Is that a problem?',
    a: `Yes — this is acknowledged as a known limitation. ScriptProcessor works in all major browsers today but may be removed in a future Chrome version. The correct replacement is AudioWorklet, which runs in a dedicated audio thread and improves performance. The migration is a planned future task. For the current deployment context (internal use, controlled browser environment), ScriptProcessor is stable. We chose not to implement AudioWorklet in this release because the migration requires a worklet script file, cross-origin isolation headers, and more complex lifecycle management — scope that does not change the core product value at this stage.`,
  },
  {
    category: 'System Design',
    flag: 'technical',
    q: 'How does the 3-second sliding window work? Why 3 seconds?',
    a: `The fusion layer collects face frames and audio chunks within a 3-second rolling window, triggered every 500ms. Three seconds balances two competing constraints: NLP analysis requires enough speech to be meaningful (a single sentence, roughly 50–80 words, typically takes 8–15 seconds, but phrase-level patterns are detectable at 2–4 seconds), and real-time responsiveness requires updates to feel live rather than lagged. The window overlap (500ms) means each update shares 83% of its input with the previous one — smoothing volatility without introducing large lag. The 3-second value was determined empirically; shorter windows produced noisy, uninterpretable outputs; longer windows made the dashboard feel disconnected from what the candidate was saying in the moment.`,
  },

  // ── Ethics and bias ───────────────────────────────────────────────────────
  {
    category: 'Ethics & Bias',
    flag: 'caution',
    q: 'Is this system biased against people with accents, disabilities, or different communication styles?',
    a: `This is a legitimate and serious concern. The honest answer is: we do not know the full extent of bias in the current system, because we have not conducted a formal demographic bias audit. What we can say: faster-Whisper (the transcription model) performs variably across accents — it is well-documented that Whisper performs better on American English than many other accents or dialects, and WER can be significantly higher for speakers with strong accents. This would degrade NLP-layer accuracy for those speakers. Facial analysis quality depends on frame quality and lighting — which disproportionately affects people with darker skin tones under poor lighting conditions (a well-documented problem in computer vision). The calibration system partially mitigates this by flagging low-quality data, but it does not solve the underlying distribution mismatch. NeuroSync should not be used as a primary filter in hiring without understanding these risks and conducting a bias audit on the deployment context.`,
  },
  {
    category: 'Ethics & Bias',
    flag: 'strength',
    q: 'What prevents NeuroSync from being used to discriminate against protected classes?',
    a: `The platform includes several structural safeguards: (1) The system measures behavioral dimensions during the session only — it does not ingest demographics, protected attributes, or historical hiring outcomes. (2) Every report includes an AI governance disclosure that decisions must not be made solely on AI output. (3) The RBAC system and immutable audit log create an accountability trail. (4) The output format is designed to present evidence, not verdicts — the recruiter sees specific behavioral signals and must apply their own judgment. However, safeguards are not substitutes for policy. Organizations deploying NeuroSync are responsible for their own compliance with employment law, EEOC guidance, and applicable AI regulation (EU AI Act, NY Local Law 144, etc.).`,
  },
  {
    category: 'Ethics & Bias',
    flag: 'caution',
    q: 'Does the system infer psychological traits or mental health conditions?',
    a: `No. NeuroSync does not claim to diagnose, infer, or assess psychological traits, personality types, or mental health conditions. It measures observable behavioral signals: speaking rate, vocal energy, word choice patterns, eye contact, and facial movement. These are proxies for in-session behavioral state — not stable personality traits. The system explicitly avoids language like "introvert", "neurotic", "anxious personality", or any clinical label. Behavioral state (e.g. "stressed" or "settled") refers to observable signal patterns in this session, not dispositional claims about the person.`,
  },

  // ── AI trust and explainability ───────────────────────────────────────────
  {
    category: 'AI Trust & Explainability',
    flag: 'strength',
    q: 'How do I know the score is based on real evidence and not just a black-box number?',
    a: `Every NeuroSync output answers six questions: (1) What happened — behavioral arc and per-dimension scores with timeline. (2) Why we believe it — evidence graph with per-modality attribution. (3) How confident — ECE-calibrated reliability tier (insufficient / low / medium / high). (4) What supports it — critical, supporting, and contextual evidence ranking per dimension. (5) What contradicts it — cross-signal contradiction detection with interpretation. (6) What should happen next — recruiter decision support with specific strengths, concerns, and review triggers. The Reasoning Inspector in the live session view surfaces the behavioral state machine, dimension trends, and calibration values in real time.`,
  },
  {
    category: 'AI Trust & Explainability',
    flag: 'technical',
    q: 'What is ECE calibration and why does it matter here?',
    a: `ECE (Expected Calibration Error) measures how well a model's stated confidence corresponds to its empirical accuracy. A perfectly calibrated model that says "I'm 80% confident" is correct approximately 80% of the time. Many neural networks are overconfident — they state high confidence on uncertain predictions. We apply post-hoc calibration (temperature scaling / Platt scaling) to correct this, then assign reliability tiers based on calibrated confidence: insufficient (< 0.3), low (0.3–0.5), medium (0.5–0.75), high (> 0.75). This matters because a recruiter needs to know whether a score of "confidence: 68%" is based on a full session with clear signals or a 90-second session with noisy audio. The tier makes this visible rather than hiding uncertainty behind a precise-looking number.`,
  },
  {
    category: 'AI Trust & Explainability',
    flag: 'strength',
    q: 'What is contradiction detection and why is it useful?',
    a: `Cross-modal contradiction detection flags when independent signal streams produce inconsistent pictures. For example: a candidate uses assertive, confident language (high NLP confidence score) but simultaneously shows physiological stress markers (elevated vocal jitter, reduced eye contact). Without contradiction detection, a naive average would produce a middling confidence score with no explanation. With it, the system surfaces: "Language signals suggest confidence while physiological markers suggest stress. This may indicate effective performance under pressure, or rehearsed responses masking uncertainty." This interpretation is more useful than a silent average — it tells the recruiter what to probe in a follow-up.`,
  },

  // ── Security ──────────────────────────────────────────────────────────────
  {
    category: 'Security & Privacy',
    flag: 'strength',
    q: 'Where does session data go? Does audio or video leave the server?',
    a: `Audio and video data are processed locally on the server where NeuroSync is deployed. Raw audio is converted to base64 PCM and transmitted over WebSocket to the backend, where transcription runs locally using faster-Whisper. Video frames are analyzed locally by MediaPipe. No raw audio, video, or transcript is transmitted to any third-party AI service. Inference is entirely self-hosted. The only external network calls in the default configuration are: loading Next.js fonts from Google Fonts (optional, can be removed) and health-check polling (internal only).`,
  },
  {
    category: 'Security & Privacy',
    flag: 'caution',
    q: 'What security measures are in place?',
    a: `Current implementation: JWT-based authentication, RBAC with 8 roles and 50+ permissions, SHA-256 chained immutable audit log, per-org data isolation. Missing in the current release: HTTPS is not enforced at the application layer (requires a reverse proxy such as nginx or Caddy), rate limiting on API endpoints, CSP headers, automated secret rotation. The Known Limitations document lists these honestly. For a production deployment at a company handling real candidate data, these gaps must be addressed before going live with real users.`,
  },

  // ── ABME and CBIP ─────────────────────────────────────────────────────────
  {
    category: 'ABME & CBIP',
    flag: 'technical',
    q: 'What is ABME and how does the EMA work?',
    a: `ABME (Adaptive Behavioral Memory Engine) maintains per-candidate behavioral profiles that update across sessions. It uses Exponential Moving Average (α=0.15) to smooth new session signals into the running profile — giving recent sessions more weight than distant ones without discarding history. For example, if a candidate's historical confidence baseline is 0.60 and the new session scores 0.74, the updated baseline = 0.15 × 0.74 + 0.85 × 0.60 = 0.62. This enables session-to-session delta tracking ("confidence has improved 8% over the last 3 sessions") without storing the full raw history. ABME never modifies model weights — it updates only the Behavioral Knowledge Layer.`,
  },
  {
    category: 'ABME & CBIP',
    flag: 'technical',
    q: 'What is CBIP? How is it different from ABME?',
    a: `ABME is per-candidate — it maintains a behavioral profile for one person across sessions. CBIP (Continual Behavioral Intelligence Platform) is cross-candidate — it accumulates platform-wide validated behavioral patterns and makes them available as coaching knowledge, archetype patterns, and organizational intelligence. CBIP uses a five-level Validation Pyramid to weight knowledge by source reliability: automatic session observations (L1, weight 0.20) up to long-term performance outcomes (L5, weight 1.00). The higher the validation level, the more influence a pattern has on CBIP's recommendations. Like ABME, CBIP never touches model weights — it operates entirely in the Knowledge Layer.`,
  },
  {
    category: 'ABME & CBIP',
    flag: 'caution',
    q: 'The forecasting predicts behavioral growth — how accurate are those forecasts?',
    a: `OLS regression on a small number of session data points (often 3–10) produces forecasts with wide confidence intervals, and we represent that honestly (±1.5σ). For a candidate with 3 sessions, the forecast is not reliable — it is a directional indicator at best. With 8–10 sessions, trend stability increases significantly. The platform displays confidence intervals on all forecasts and marks projections with fewer than 4 data points as low-confidence. The design principle is that forecasts predict behavioral trajectory only, never job performance or hiring outcomes, and are presented as supplementary context for long-term coaching relationships, not as decision inputs.`,
  },
]

const CATEGORIES = Array.from(new Set(FAQS.map(f => f.category)))

// ── FAQ Item ──────────────────────────────────────────────────────────────────

function FAQItem({ faq }: { faq: FAQ }) {
  const [open, setOpen] = useState(false)

  return (
    <div className={cn(
      'rounded-xl border transition-all duration-150',
      open ? 'border-border-active bg-bg-card' : 'border-border bg-bg-card hover:border-border-active',
    )}>
      <button
        onClick={() => setOpen(v => !v)}
        className="w-full flex items-start gap-3 px-5 py-4 text-left"
      >
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            {faq.flag === 'caution' && (
              <AlertCircle className="w-3.5 h-3.5 text-status-warning flex-shrink-0" />
            )}
            {faq.flag === 'strength' && (
              <CheckCircle className="w-3.5 h-3.5 text-status-success flex-shrink-0" />
            )}
            <p className="text-sm font-semibold text-text-primary leading-snug">{faq.q}</p>
          </div>
        </div>
        {open
          ? <ChevronUp className="w-4 h-4 text-text-muted flex-shrink-0 mt-0.5" />
          : <ChevronDown className="w-4 h-4 text-text-muted flex-shrink-0 mt-0.5" />}
      </button>

      {open && (
        <div className="px-5 pb-5 border-t border-border-subtle pt-4">
          {typeof faq.a === 'string' ? (
            <p className="text-sm text-text-secondary leading-relaxed">{faq.a}</p>
          ) : (
            faq.a
          )}
        </div>
      )}
    </div>
  )
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default function FAQPage() {
  const [activeCategory, setActiveCategory] = useState<string | null>(null)

  const filtered = activeCategory
    ? FAQS.filter(f => f.category === activeCategory)
    : FAQS

  const cautionCount  = FAQS.filter(f => f.flag === 'caution').length
  const strengthCount = FAQS.filter(f => f.flag === 'strength').length

  return (
    <AppShell title="Technical FAQ">
      <div className="p-6 max-w-4xl space-y-8">

        {/* Header */}
        <div>
          <h1 className="text-2xl font-bold text-text-primary tracking-tight mb-2">Technical FAQ</h1>
          <p className="text-sm text-text-secondary leading-relaxed max-w-2xl">
            Honest answers to hard questions about NeuroSync — model validity, system design, ethics, bias, security, and limitations.
            Questions marked <AlertCircle className="w-3 h-3 text-status-warning inline mx-0.5" /> are areas of genuine limitation.
            Questions marked <CheckCircle className="w-3 h-3 text-status-success inline mx-0.5" /> are areas of considered strength.
          </p>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-3 gap-4">
          <div className="rounded-xl border border-border bg-bg-card px-4 py-3">
            <p className="text-xl font-bold text-text-primary">{FAQS.length}</p>
            <p className="text-xs text-text-muted mt-0.5">Questions answered</p>
          </div>
          <div className="rounded-xl border border-status-warning/20 bg-status-warning/5 px-4 py-3">
            <div className="flex items-center gap-1.5">
              <AlertCircle className="w-3.5 h-3.5 text-status-warning" />
              <p className="text-xl font-bold text-status-warning">{cautionCount}</p>
            </div>
            <p className="text-xs text-text-muted mt-0.5">Honest limitations</p>
          </div>
          <div className="rounded-xl border border-status-success/20 bg-status-success/5 px-4 py-3">
            <div className="flex items-center gap-1.5">
              <CheckCircle className="w-3.5 h-3.5 text-status-success" />
              <p className="text-xl font-bold text-status-success">{strengthCount}</p>
            </div>
            <p className="text-xs text-text-muted mt-0.5">Design strengths</p>
          </div>
        </div>

        {/* Category filter */}
        <div className="flex flex-wrap gap-2">
          <button
            onClick={() => setActiveCategory(null)}
            className={cn(
              'px-3 py-1.5 rounded-lg text-xs font-medium transition-colors',
              activeCategory === null
                ? 'bg-accent-glow text-accent border border-accent/20'
                : 'text-text-muted border border-border hover:border-border-active hover:text-text-secondary',
            )}
          >
            All ({FAQS.length})
          </button>
          {CATEGORIES.map(cat => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat === activeCategory ? null : cat)}
              className={cn(
                'px-3 py-1.5 rounded-lg text-xs font-medium transition-colors',
                activeCategory === cat
                  ? 'bg-accent-glow text-accent border border-accent/20'
                  : 'text-text-muted border border-border hover:border-border-active hover:text-text-secondary',
              )}
            >
              {cat} ({FAQS.filter(f => f.category === cat).length})
            </button>
          ))}
        </div>

        {/* FAQ list */}
        <div className="space-y-3">
          {activeCategory && (
            <p className="text-xs font-semibold uppercase tracking-widest text-text-disabled">{activeCategory}</p>
          )}
          {filtered.map((faq, i) => (
            <FAQItem key={i} faq={faq} />
          ))}
        </div>

        {/* Footer links */}
        <div className="pt-4 border-t border-border flex flex-wrap gap-4">
          <Link href="/architecture" className="flex items-center gap-1.5 text-xs text-text-muted hover:text-accent transition-colors">
            Architecture deep-dive
            <ExternalLink className="w-3 h-3" />
          </Link>
          <Link href="/governance" className="flex items-center gap-1.5 text-xs text-text-muted hover:text-accent transition-colors">
            AI Governance policy
            <ExternalLink className="w-3 h-3" />
          </Link>
          <Link href="/benchmarks" className="flex items-center gap-1.5 text-xs text-text-muted hover:text-accent transition-colors">
            Model benchmarks
            <ExternalLink className="w-3 h-3" />
          </Link>
        </div>

      </div>
    </AppShell>
  )
}
