"""
Authentication service.

Handles:
  - User registration + email/password auth
  - Session token generation + validation (no JWT dependency — simple signed tokens)
  - Password hashing via hashlib PBKDF2-SHA256 (no bcrypt required)
  - Session expiry + revocation
  - Last-login tracking

Token format: "<user_id>:<session_token>" stored in the auth_sessions table.
The raw token is a 48-byte hex string (256 bits), generated by secrets.token_hex.

Future: swap token generation for JWT when enterprise SSO / OIDC is needed.
"""

from __future__ import annotations

import hashlib
import hmac
import logging
import secrets
import time
import uuid
from typing import Optional

from backend.authentication.models import AuthSession, TokenPair, User
from backend.services.enterprise_db import get_enterprise_conn

logger = logging.getLogger("neurosync.auth")

_TOKEN_TTL_S  = 3600          # access token: 1 hour
_REFRESH_TTL_S = 86400 * 30  # refresh: 30 days
_PBKDF2_ITERS  = 260_000


def _hash_password(password: str) -> str:
    """PBKDF2-SHA256 with a random 16-byte salt. Returns '{salt_hex}:{dk_hex}'."""
    salt = secrets.token_bytes(16)
    dk   = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, _PBKDF2_ITERS)
    return f"{salt.hex()}:{dk.hex()}"


def _verify_password(password: str, stored: str) -> bool:
    try:
        salt_hex, dk_hex = stored.split(":", 1)
        salt = bytes.fromhex(salt_hex)
        dk   = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, _PBKDF2_ITERS)
        return hmac.compare_digest(dk.hex(), dk_hex)
    except Exception:
        return False


class AuthService:
    # ── User Management ───────────────────────────────────────────────────────

    def register(
        self,
        tenant_id:    str,
        email:        str,
        password:     str,
        display_name: str = "",
        org_id:       Optional[str] = None,
    ) -> User:
        user_id    = f"usr_{uuid.uuid4().hex[:12]}"
        pwd_hash   = _hash_password(password)
        created_at = time.time()
        con = get_enterprise_conn()
        try:
            con.execute(
                """
                INSERT INTO users
                  (user_id, tenant_id, org_id, email, password_hash, display_name,
                   status, mfa_enabled, created_at)
                VALUES (?, ?, ?, ?, ?, ?, 'active', 0, ?)
                """,
                (user_id, tenant_id, org_id, email.lower().strip(),
                 pwd_hash, display_name or email.split("@")[0], created_at),
            )
            con.commit()
            logger.info("User registered: %s (%s) tenant=%s", email, user_id, tenant_id)
            return User(
                user_id=user_id, tenant_id=tenant_id, org_id=org_id,
                email=email, display_name=display_name, status="active",
                mfa_enabled=False, created_at=created_at,
            )
        finally:
            con.close()

    def get_by_email(self, tenant_id: str, email: str) -> Optional[User]:
        con = get_enterprise_conn()
        try:
            row = con.execute(
                "SELECT * FROM users WHERE tenant_id = ? AND email = ? AND status != 'deleted'",
                (tenant_id, email.lower().strip()),
            ).fetchone()
            return User.from_row(row) if row else None
        finally:
            con.close()

    def get_by_id(self, user_id: str) -> Optional[User]:
        con = get_enterprise_conn()
        try:
            row = con.execute(
                "SELECT * FROM users WHERE user_id = ? AND status != 'deleted'",
                (user_id,),
            ).fetchone()
            return User.from_row(row) if row else None
        finally:
            con.close()

    def list_for_org(self, tenant_id: str, org_id: str) -> list:
        con = get_enterprise_conn()
        try:
            rows = con.execute(
                "SELECT * FROM users WHERE tenant_id = ? AND org_id = ? AND status != 'deleted' ORDER BY display_name",
                (tenant_id, org_id),
            ).fetchall()
            return [User.from_row(r) for r in rows]
        finally:
            con.close()

    # ── Authentication ────────────────────────────────────────────────────────

    def login(
        self,
        tenant_id:  str,
        email:      str,
        password:   str,
        ip_address: str = "",
        user_agent: str = "",
    ) -> Optional[TokenPair]:
        con = get_enterprise_conn()
        try:
            row = con.execute(
                "SELECT * FROM users WHERE tenant_id = ? AND email = ? AND status = 'active'",
                (tenant_id, email.lower().strip()),
            ).fetchone()
        finally:
            con.close()

        if row is None:
            return None
        if not _verify_password(password, row["password_hash"] or ""):
            return None

        return self._issue_tokens(
            user_id   = row["user_id"],
            tenant_id = tenant_id,
            ip_address = ip_address,
            user_agent = user_agent,
        )

    def _issue_tokens(
        self, user_id: str, tenant_id: str, ip_address: str, user_agent: str
    ) -> TokenPair:
        access_token  = secrets.token_hex(32)
        refresh_token = secrets.token_hex(48)
        now           = time.time()
        con = get_enterprise_conn()
        try:
            con.execute(
                """
                INSERT INTO auth_sessions
                  (session_token, user_id, tenant_id, created_at, expires_at, ip_address, user_agent)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (access_token, user_id, tenant_id, now, now + _TOKEN_TTL_S, ip_address, user_agent),
            )
            con.execute(
                "UPDATE users SET last_login = ? WHERE user_id = ?",
                (now, user_id),
            )
            con.commit()
        finally:
            con.close()
        return TokenPair(
            access_token  = access_token,
            refresh_token = refresh_token,
            expires_in    = _TOKEN_TTL_S,
        )

    def validate_token(self, token: str) -> Optional[AuthSession]:
        con = get_enterprise_conn()
        try:
            row = con.execute(
                "SELECT * FROM auth_sessions WHERE session_token = ? AND revoked = 0",
                (token,),
            ).fetchone()
            if row is None:
                return None
            session = AuthSession(
                session_token = row["session_token"],
                user_id       = row["user_id"],
                tenant_id     = row["tenant_id"],
                created_at    = row["created_at"],
                expires_at    = row["expires_at"],
                ip_address    = row["ip_address"] or "",
                revoked       = bool(row["revoked"]),
            )
            return session if session.is_valid() else None
        finally:
            con.close()

    def revoke_token(self, token: str) -> bool:
        con = get_enterprise_conn()
        try:
            cur = con.execute(
                "UPDATE auth_sessions SET revoked = 1 WHERE session_token = ?", (token,)
            )
            con.commit()
            return cur.rowcount > 0
        finally:
            con.close()

    def revoke_all_user_sessions(self, user_id: str) -> int:
        con = get_enterprise_conn()
        try:
            cur = con.execute(
                "UPDATE auth_sessions SET revoked = 1 WHERE user_id = ? AND revoked = 0",
                (user_id,),
            )
            con.commit()
            return cur.rowcount
        finally:
            con.close()

    def update_password(self, user_id: str, new_password: str) -> bool:
        con = get_enterprise_conn()
        try:
            cur = con.execute(
                "UPDATE users SET password_hash = ? WHERE user_id = ?",
                (_hash_password(new_password), user_id),
            )
            con.commit()
            return cur.rowcount > 0
        finally:
            con.close()

    def update_status(self, user_id: str, status: str, actor_id: str) -> bool:
        allowed = {"active", "suspended", "deleted", "pending"}
        if status not in allowed:
            raise ValueError(f"Invalid user status: {status}")
        con = get_enterprise_conn()
        try:
            cur = con.execute(
                "UPDATE users SET status = ? WHERE user_id = ?",
                (status, user_id),
            )
            con.commit()
            if cur.rowcount and status in ("suspended", "deleted"):
                self.revoke_all_user_sessions(user_id)
            return cur.rowcount > 0
        finally:
            con.close()


auth_service = AuthService()
